#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
radio_delay

Delays a sports radio broadcast by an adjustable amount to sync up with TV.
"""

import sys
import argparse

def radio_delay(delay):
    """
    Send delayed sound input to sound output

    Arguments:
        delay: Delay in seconds
    """

    pass


if __name__ == '__main__':
    def main(cmdln_args):
        """
        Set up and parse arguments

        Arguments:
            cmdln_args: List of command line arguments (excluding script name)
        """

        # Parse arguments with argparse
        formatter_class = argparse.ArgumentDefaultsHelpFormatter

        parser = argparse.ArgumentParser(description=__doc__,
                                         formatter_class=formatter_class)

        parser.add_argument('--delay',
                            help="Delay (in seconds)",
                            default=60,
                            type=int)

        args = parser.parse_args(cmdln_args)

        radio_delay(args.delay)

    # Call main() with parsed args
    sys.exit(main(sys.argv[1:]))
